
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        show_sql: true
    open-in-view: false
    generate-ddl: false
  application:
    name: order api spring
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  datasource:
    url: jdbc:mariadb://localhost:3306/order
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${name}
    password: ${pw}
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:~/test;MODE=MYSQL;
#    username: sa
#    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: maria-db
server:
  port: 8080
jwt:
  access-token:
    secret-key: Rel3Bjce2MajBo09qgkNgYaTuzvJe8iwnBFhsDS5

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
#    operations-sorter: alpha
#    tags-sorter: alpha
  default-consumes-media-type: application/json
