
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        show_sql: true
    open-in-view: false
    generate-ddl: false
  application:
    name: order api spring
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;MODE=MYSQL;
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
server:
  port: 8080
jwt:
  header: X-AUTH
  access-token:
    secret-key: Rel3Bjce2MajBo09qgkNgYaTuzvJe8iwnBFhsDS5
#  token:
#    header: X-PRGRMS-AUTH
#    issuer: programmers
#    client-secret: Rel3Bjce2MajBo09qgkNgYaTuzvJe8iwnBFhsDS5
#    expiry-seconds: 0
